service:
    name: notion-boy
    host: "0.0.0.0"
    port: 8001
    url: http://localhost:8001

wechat:
    appID:
    appSecret:
    token:
    encodingAesKey:
    # 作者的微信二维码在素材库中的 ID，用于 SOS 返回作者个人的微信
    authorID:
    adminUserID:

database:
    driver: sqlite
    sqlite:
        file: data.db
    mysql:
        host:
        port:
        user:
        pass:
        db:

notionTestPage:
    DatabaseID:
    Token:

r2:
    url:
    token:

storage:
    endpoint:
    accessKey:
    secretKey:
    region:
    bucketName:
    domain:

log:
    level: info
# devToolsURL: ws://browserless:3000

chatGPT:
    apiKey:
    model:

telegram:
    token:

zlib:
    host:
    ipfsGateways:
        - https://ipfs.io
        - https://cloudflare-ipfs.com
        - https://ipfs.infura.io
        - https://dweb.link
        - https://gateway.pinata.cloud
        - https://cf-ipfs.com

readability:
    host:

jwt:
    SigningKey: example key must be changed
    ExpireTime: 3600

oauth:
    github:
        clientID:
        clientSecret:
        state:
    notion:
        clientID:
        clientSecret:
        urlRedirect:
        authUrl: https://api.notion.com/v1/oauth/authorize?owner=user
        authToken: https://api.notion.com/v1/oauth/token
        state:
